### ISSUE TITLE
Missing newlines in 0-rawreads/daligner-split/run_jobs.sh

### ISSUE THREAD

**Issue by bruc** [PacificBiosciences/pbbioconda#14]
In a test run of pb-assembly, I found a shell script that looks like it's missing newlines between each command. The file was in

    0-rawreads/daligner-split

and named ```run_jobs.sh ```

and the only line begins like this:
```
rm raw_reads.1.raw_reads.*.lasrm raw_reads.2.raw_reads.*.lasrm raw_reads.3.raw_reads.*.lasrm
```

**Comment by armintoepfer** [comment]
Thank you, I forwarded it internally and we are looking into it.

**Comment by pb-cdunn** [comment]
Reproduced. Working on it...

**Comment by pb-cdunn** [comment]
This is some kind of bug in Gene's **HPC.daligner**. When I run this:

    HPC.daligner -P. -h1 -e.99 -w1 -l1 -s1000 -v -B4 -t50 -mdust -mrep0 -mtan -H2000 -fdaligner-jobs raw_reads

it generates:
```
daligner-jobs.01.OVL
daligner-jobs.02.CHECK.OPT
daligner-jobs.03.MERGE
daligner-jobs.04.RM.OPT
```
as excepted, but it also writes that strange line to stdout.

We do not actually use the `run_jobs.sh` from stdout anymore, so this harms nothing. But when I get a chance, I'll get rid of `run_jobs.sh`, and I'll check whether this is oddity is fixed in Gene's upstream repo...

... No, not fixed upstream. This is a little bug with Gene's `-f` flag...

**Comment by pb-cdunn** [comment]
https://github.com/thegenemyers/DALIGNER/pull/87

**Comment by pb-cdunn** [comment]
Not sure if Gene has fixed this upstream. No response.

We could fix this in our fork, but as it does not actually affect anyone, I'll close this.
