### ISSUE TITLE
Help understanding Quiver output

### ISSUE THREAD

**Issue by pjedge** [PacificBiosciences/pbbioconda#142]
Hi, I ran Quiver in --diploid mode and it produced a VCF with variants but without any sample field. I.e no GT, GQ, etc. I was expecting a single sample field with (presumably diploid) GT since it was run in diploid mode. Is what happened the expected behavior for quiver (find variants but not genotype)?

**Comment by armintoepfer** [comment]
Given the latest scientific insights, I recommend using GATK or DeepVariant for SNV calling. But as you pointed out, your data is ancient, because it's from RSII. In general, I do not recommend putting too much faith into the VCFs produced by variantcaller, because they are not spec compliant and have a few underlying problems. 

That said, we can't provide in-depth support for outdated software on pbbioconda. Please contact PacBio directly. Sorry that I can't help you further.
