### ISSUE TITLE
Error in step 3-unzip/reads

### ISSUE THREAD

**Issue by cguyomar** [PacificBiosciences/pbbioconda#175]
I am running falcon unzip on a previous Falcon assembly of a plant genome, but is stops in the step 3-unzip/reads
I went the repository for this step and tried to run user_script.sh
The failing command appears to be : 
`python3 -m falcon_unzip.mains.fetch_reads --p-ctg=../../2-asm-falcon/p_ctg.fa --fofn=../../../../../../../data/idiv_biu/guyomar/stipa/falcon/input.fofn --ctg-list=ctg_list`

For which I get this output : 
```falcon-unzip 1.3.4 (pip thinks "falcon-unzip 1.3.4")
falcon-kit 1.4.4
pypeflow 2.3.0
[INFO 2019-08-13 09:44:41,866 GMT] Counting 799,913,399 bytes from
  "/gpfs1/work/cuyomar/stipa/falcon/2-asm-falcon/p_ctg.fa"
[INFO 2019-08-13 09:44:41,896 GMT]         #1 count=        588,047   0.07% 
[INFO 2019-08-13 09:44:41,910 GMT]         #3 count=      1,687,252   0.21% 
[INFO 2019-08-13 09:44:41,926 GMT]         #6 count=      3,274,401   0.41% 
[INFO 2019-08-13 09:44:41,952 GMT]        #11 count=      5,813,934   0.73% 
[INFO 2019-08-13 09:44:42,014 GMT]        #21 count=     10,546,100   1.32% 
[INFO 2019-08-13 09:44:42,114 GMT]        #44 count=     19,995,311   2.50% 
[INFO 2019-08-13 09:44:42,337 GMT]        #99 count=     38,955,150   4.87% 
[INFO 2019-08-13 09:44:42,844 GMT]       #231 count=     76,661,029   9.58% 
[INFO 2019-08-13 09:44:44,011 GMT]       #555 count=    152,102,039  19.01% 
[INFO 2019-08-13 09:44:45,479 GMT]       #983 count=    232,226,628  29.03% 
[INFO 2019-08-13 09:44:47,279 GMT]     #1,502 count=    312,321,828  39.04% 
[INFO 2019-08-13 09:44:49,299 GMT]     #2,125 count=    392,366,403  49.05% 
[INFO 2019-08-13 09:44:51,598 GMT]     #2,875 count=    472,367,768  59.05% 
[INFO 2019-08-13 09:44:54,337 GMT]     #3,800 count=    552,427,341  69.06% 
[INFO 2019-08-13 09:44:57,819 GMT]     #5,007 count=    632,460,038  79.07% 
[INFO 2019-08-13 09:45:02,646 GMT]     #6,754 count=    712,459,118  89.07% 
[INFO 2019-08-13 09:45:08,307 GMT]    #10,169 count=    792,460,173  99.07% 
[INFO 2019-08-13 09:45:24,938 GMT] Counting bytes from "/data/idiv_biu/guyomar/stipa/data/m54198_190309_021722.fasta.gz"
Traceback (most recent call last):
  File "/home/cuyomar/soft/env_pb-assembly/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/cuyomar/soft/env_pb-assembly/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/cuyomar/soft/env_pb-assembly/lib/python3.6/site-packages/falcon_unzip/mains/fetch_reads.py", line 189, in <module>
    main()
  File "/home/cuyomar/soft/env_pb-assembly/lib/python3.6/site-packages/falcon_unzip/mains/fetch_reads.py", line 185, in main
    fetch_ref_and_reads(**vars(args))
  File "/home/cuyomar/soft/env_pb-assembly/lib/python3.6/site-packages/falcon_unzip/mains/fetch_reads.py", line 109, in fetch_ref_and_reads
    for r in read_fa_file:
  File "/home/cuyomar/soft/env_pb-assembly/lib/python3.6/site-packages/falcon_kit/FastaReader.py", line 182, in yield_fasta_record
    assert "" == next(parts)
  File "/home/cuyomar/soft/env_pb-assembly/lib/python3.6/site-packages/falcon_kit/FastaReader.py", line 57, in splitFileContents
    parts = block.split(delimiter)
TypeError: a bytes-like object is required, not 'str'
```

Thanks for the help.

**Comment by pb-cdunn** [comment]
First, you're better off if you start with a `python=3.7` conda-env.

More import, at the top I see:
```
falcon-kit 1.4.4
pypeflow 2.3.0
```
But nothing for `falcon_unzip`? We have this code in `falcon_unzip/__init__.py`:
```py
__version__ = '1.3.4'

try:
    import sys, pkg_resources
    sys.stderr.write('falcon-unzip {} (pip thinks "{}")\n'.format(__version__, pkg_resources.get_distribution('falcon-unzip')))except Exception:
    pass
```
But that is not being printed. So you must be using an old version of Unzip.

By far, the most common problem is simply the conda environment. You will see in the Issue submission guidelines (last I checked) that we request the result of `conda list`. That is very important so that we can avoid spending time debugging integration problems. My guess is that you will see an old version of `unzip`. Possibly that is because the more recent version is not compatible with py3.6. Not sure. Or maybe you are getting `falcon_unzip` from somewhere else entirely.

The specific problem is seen here:
```py
% python3
>>> b'1.2'.split('.')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: a bytes-like object is required, not 'str'
>>> b'1.2'.split(b'.')
[b'1', b'2']
```
* https://stackoverflow.com/questions/50829364/cannot-split-a-bytes-like-object-is-required-not-str

This would happen if `open_fasta_reader()` used a binary `mode` to open the fasta file. But I do not see how that could be possible. The `mode` is always `r` (non-binary). So we might need your help debugging this.

But the first thing to check is definitely your version of **falcon_unzip**.

If this turns out to be a real bug with the latest code, please re-open. We would want to solve that quickly. Maybe step into the code in a debugger to see how the file was opened (probably in `FastaReader.py::open_fasta_reader()`). Then watch the datatypes in `splitFileContents()`. Good luck.

**Comment by cguyomar** [comment]
Thanks for your input.

The falcon unzip message was missing for a simple copy/paste problem. Everything seems up to date.
I also updated to Python 3.7.

I observed that the problem did not occurred  while reading the contigs file (in .fa format), but did for the first readset (in fa.gz).

Based on : https://docs.python.org/3/library/gzip.html , gzip.open requires different modes for non binary files.
Replacing mode="r" by "rt" for .gz files in 'open_fasta_reader' apparently fixed the issue.
```
    if filename.endswith(".gz"):
        mode='rt'
        ofs = gzip.open(filename, mode)
```

This probably should be fixed.

**Comment by clsaetre** [comment]
Hi! 
I'm a beginner, so I'm sorry in advance for my ignorance. I think I may have the same problem, but I don't understand what you are referring to here: "Replacing mode="r" by "rt" for .gz files in 'open_fasta_reader' apparently fixed the issue." 

What is open_fasta_reader and where could I find it?

Best regards,
Camilla

**Comment by clsaetre** [comment]
Thank you! I found it.


All the best,

Camilla


________________________________
