### ISSUE TITLE
DBsplit options for large genomes

### ISSUE THREAD

**Issue by AdamStuckert** [PacificBiosciences/pbbioconda#180]
We are assembling a genome that is > 6 Gbp in size, and we are wondering what the best DBsplit flags are for our purposes. The readme says:

```# large genomes
pa_DBsplit_option=-x500 -s200
ovlp_DBsplit_option=-x500 -s200

# small genomes (<10Mb)
pa_DBsplit_option = -x500 -s50
ovlp_DBsplit_option = -x500 -s50
```

Does this mean that everything > 10 Mb should have the `x500 -s200` option, or should this be adjusted for much larger genomes?

Thanks in advance!

**Comment by harish0201** [comment]
Hi!

I'm sorry to necro-bump this issue up, but I was wondering about the same, is there a way to prune the folders/files created during Falcon?

So, far the daligner-runs have finished and I'm looking at nearly 13Tb worth of files in a 16Tb drive. 

````
pa_DBsplit_option=-x500 -s400
ovlp_DBsplit_option=-s400
`````

Is there are parameter otherwise that will prune the files generated?

**Comment by pb-cdunn** [comment]
Try

    falconc pbcromwell-rm-las -h

That is designed for use with our Cromwell workflow, but it should work for you too. Be sure to run in "dry-run" mode first.
