### ISSUE TITLE
number of jobs is increasing

### ISSUE THREAD

**Issue by michaeljmetzger** [PacificBiosciences/pbbioconda#199]
I am running FALCON on an ~1.6GB genome. When using the script recommended for checking job progress during the daligner stage I got 747 total jobs. After a few days of running, the number of completed jobs got to 747, but then the total just bumped up to 1510 and it kept running more jobs. Is this normal? Is there any way to tell how long it will really take?

The command used for total jobs is:
ls 0-rawreads/daligner-chunks/ | wc -l
The command for completed jobs is:
find 0-rawreads/daligner-runs/j_*/uow-00 -name "daligner.done" | wc -l
based on the page: https://github.com/PacificBiosciences/pb-assembly

Thanks,
Michael

**Comment by michaeljmetzger** [comment]
UPDATE: It finished the 0-rawreads/daligner tasks after the 1510 jobs. Now working on the 1-preads_ovl/daligner. There seems to be no method of determining how long the rest of this will take, but at least it is continuing to do things.

**Comment by pb-cdunn** [comment]
Yes, that's normal. The task-graph is dynamic, which is good and bad. Easy to work with, but not predictable.

The number daligner runs will be `N*N`, where `N` is the number of blocks in `build/raw_reads.db`. If you watch a single daligner run, and divide its runtime by twice the number of blocks it compared (since it compares A to B and B to A), you can divide that into `N*N` to estimate the total runtime of daligner.
