### ISSUE TITLE
isoseq3 polish SIGABRT using v3.2.2

### ISSUE THREAD

**Issue by stekaz** [PacificBiosciences/pbbioconda#200]
**Operating system**
x86_64 GNU/Linux

**Package name**
isoseq3 3.2.2 (commit v3.2.2)

**Conda environment**
```
# packages in environment at /working/share/containers/conda/env-1e8a3b53cd5606a21fe1babb719eed08:
#
# Name                    Version                   Build  Channel
isoseq3                   3.2.2                         0    bioconda
```

**Describe the bug**
The 'polish' sub-command exits 134 using the latest release (3.2.2-0). Please see below. I think this may be related to #194, but I am also hitting this issue using 3.2.1-3. So maybe this is a dependency issue? The last release where 'polish' runs uninterrupted appears to be 3.1.2-0. Using 3.2.0-0 may provide a clue:

```
>|> 20190925 01:33:39.109 -|- FATAL -|- operator() at ../subprojects/pbcopper/src/logging/Logging.cpp:49 -|- 0x7f6e74ddd780|| -|- caught SIGABRT
```

**Error message**
```
>|> 20190925 00:52:41.939 -|- FATAL -|- operator() -|- 0x7f61d0100780|| -|- caught SIGABRT
  polish.sh: line 9: 121377 Aborted                 (core dumped) isoseq3 polish --num-threads 8 --verbose --rq-cutoff "0.99" --coverage "60" "test_library.unpolished.bam" "test_library.subreadset.xml" "test_library.polished.bam"
```

**To Reproduce**

Unpack:

[test.tar.gz](https://github.com/PacificBiosciences/pbbioconda/files/3650313/test.tar.gz)

Then:

```
$ isoseq3 --version
isoseq3 3.2.2 (commit v3.2.2)
$ isoseq3 polish --num-threads 1 --verbose test_library.unpolished.bam test_library.subreadset.xml test_library.polished.bam
>|> 20190925 02:37:18.145 -|- FATAL -|- operator() -|- 0x7fdadbdba780|| -|- caught SIGABRT
Aborted (core dumped)
```

**Comment by armintoepfer** [comment]
Thank you for taking the time to report this issue and put together a test dataset!

This problem is definitely a lack of my communication in the docs. With the upcoming SMRT Link release which contains Iso-Seq v3.2, we stopped supporting RSII data across all tools that polish (CCS, Iso-Seq, GenomicConsensus). I absolutely agree that this should throw an error and tell you that your data is not supported any longer.
But here is the upside, we haven't changed anything in the polish step, so if you use RSII data, please stick with Iso-Seq v3.1!

I will adjust the documentation and add a warning. Thanks again.

**Comment by stekaz** [comment]
Thanks very much for the speedy reply, @armintoepfer, that makes perfect sense now, cheers!

**Comment by armintoepfer** [comment]
I've added warnings to the changelog: https://github.com/PacificBiosciences/IsoSeq#changelog
and first paragraph of v3.2: https://github.com/PacificBiosciences/IsoSeq/blob/master/README_v3.2.md
