### ISSUE TITLE
arrow:  "ReadGroupInfo: basecaller version is too short: "

### ISSUE THREAD

**Issue by CristianRiccio** [PacificBiosciences/pbbioconda#213]
**Operating system**
GNU/Linux

**Package name**
pbgcpp version 1.0.0

**Conda environment**
conda list
packages in environment at /mnt/home2/group/user/anaconda3/envs/pbgcpp1_0_0:
Name                    Version                   Build  Channel
pbgcpp                    1.0.0                         0    bioconda

**Describe the bug**
arrow complains about the basecaller version, probably in the BAM file. Indeed, there is no read group basecaller in the BAM file. Example of alignment line in the BAM file:
```
m54097_170511_115331/4457083/0_13723    16      tig00000064     330920  60      2S20=2X10=2X1=2X11=1X2=8I3=6I4=1I1X12=1D4=2D24=3I8=2I5=1D2=2D3=
```
But I used the pbmm2 package to create this alignment, so I expected the BAM to respect arrow's rules.

**Error message**
```
>|> 20191008 14:35:13.676 -|- FATAL -|- operator() -|- 0x7ffb7feef780|| -|- caught exception: "ReadGroupInfo: basecaller version is too short: "
>|> 20191008 14:35:13.676 -|- FATAL -|- operator() -|- 0x7ffb7feef780|| -|- caught SIGABRT
/var/lib/slurm-llnl/slurmd/job3624692/slurm_script: line 10: 54953 Aborted                 gcpp --reference genome.fa --output arrow.fa pacbio2genome.bam
```

**Expected behavior**
A polished version of the assembly.

**Comment by pb-dseifert** [comment]
...did you use a subreads BAM or FASTQ as input to `pbmm2`?

**Comment by CristianRiccio** [comment]
Used .fa file, oops? This is the command I used: `pbmm2 align {input.index} {input.reads} {output.aln}`

**Comment by pb-dseifert** [comment]
Current pbmm2 outputs
```
>|> 20191008 15:15:22.399 -|- WARN -|- CheckPositionalArgs -|- 0x1145aa5c0|| -|- Input is FASTA. Output BAM file cannot be used for polishing with GenomicConsensus!
```
when you align FASTA or FASTQ files. You have to align the subreads BAM.

**Comment by yinshiyi** [comment]
@pb-dseifert 
Hi expert, I would like to follow up quickly on your insightful comments.
I have both 1) subreads and also 2) generated HiFi reads in fastq format. 
I thought it is best to use HiFi reads to align to genome since it is already called by ccs which could be more accurate. 
Wondering what is the best practice here? do you often use subreads directly and skip the HiFi reads?
And what is the deal with HiFi reads in bam format? that is a bit weird to me, it might be my nanopore background is biased my habits.

Many thanks

**Comment by pb-dseifert** [comment]
@yinshiyi we don't support running `gcpp` anymore using CLR or Hifi data. If you want to polish assemblies, consider using something like racon, but `gcpp` is EOL at this point.

**Comment by PollyHung** [comment]
Dear @pb-dseifert 

I currently have the following raw data available: `subreads.fasta` and `subreads.fastq` probably resulting from the `bam2fasta` and `bam2fastq` function on `subreads.bam`. Beginning with these two files, the final output I would like to achieve out of IsoSeq pipeline is a GTF file which would be used as the input file of SQANTI. I have tried using `pbmm2` to first re-construct the `subreads.bam` and then use that to generate `hifi_reads.bam` for downstream [isoseq analysis](https://isoseq.how/clustering/cli-workflow.html). 

However because I do not have the metadata for the bam file I am encountering unmatched chemical info warning. This is my code, 
```
# create fasta unzipped and fofn file of fastq
gunzip -c "$fasta" > "$fasta_unzipped"
echo "$fastq" > "$fofn_file"

# run pbmm2 
$pbmm2 align "$fasta_unzipped" "$fofn_file" "$subread_bam" --sort -j 72 --preset SUBREAD --log-level DEBUG --rg '@RG\tID:0700181A\tSM:0700181A\tDS:READTYPE=SUBREAD;BINDINGKIT=101490800;SEQUENCINGKIT=101491000;BASECALLERVERSION=5.0;FRAMERATEHZ=100'
chmod +x "$subread_bam" 

$pbmm2 align "$fasta_unzipped" "$subread_bam" "$movie_bam" --preset SUBREAD --sort -j 72 --log-level DEBUG 
chmod +x "$movie_bam"

# ccs 
$ccs $movie_bam $reads_bam --all --log-level INFO -j 72 --reportFile $report_csv --logFile $log_txt
```
and this is the log_txt I got in return 
```
| 20240524 13:51:26.650 | INFO | Effective commandline     : /rds/general/user/ph323/home/anaconda3/envs/Renv/bin/ccs 0700055A.subreads.bam 0700055A.reads.bam --all --log-level INFO -j 64 --reportFile 0700055A.ccs_report.csv --logFile 0700055A.mylog.txt
| 20240524 13:51:26.650 | INFO | CCS Version               : 6.4.0 (commit v6.4.0)
| 20240524 13:52:26.592 | FATAL | ccs ERROR: [pbbam] read group ERROR: basecaller version is too short: 
```

Therefore I was wondering is there any other way I could resolve this issue or spin out a ccs produced hifi_reads.bam for the isoseq pipeline?
