### ISSUE TITLE
isoseq3 cluster and polish (version 3.2)

### ISSUE THREAD

**Issue by emaleckova** [PacificBiosciences/pbbioconda#222]
Dear Armin,

I have a question regarding the current clustering/polishing step and would appreciate if you could answer it for me. Regarding isoseq3 cluster, the Github Readme says:

> Output: The following output files of _cluster_ contain polished isoforms:

> <prefix>.bam
> <prefix>.hq.fasta.gz with predicted accuracy ≥ 0.99
> <prefix>.lq.fasta.gz with predicted accuracy < 0.99
> <prefix>.bam.pbi
> <prefix>.transcriptset.xml

However, when I call help for isoseq3 cluster, the following is displayed:

> isoseq cluster - Cluster FLNC reads and generate unpolished transcripts (FLNC to UNPOLISHED)
> Usage:
> isoseq cluster [options] <flnc.bam|xml> <unpolished.bam|xml>

My concern thus is, what the actual outcome of `isoseq3 cluster` is. Do I still need to run `isoseq3 polish` subsequently or would it be redundant or even biasing the resulting sequences somehow?

Thank you very much for your response.

Best regards,
Eva

**Comment by armintoepfer** [comment]
Hi Eva,

from your quotes it sounds like you follow [this guide for v3.2](https://github.com/PacificBiosciences/IsoSeq/blob/master/README_v3.2.md)?

The wording is tricky, because `cluster` can be used with both, unpolished CCS reads or polished CCS reads. If you use polished CCS reads as input to the workflow, you stop after clustering, whereas if you used unpolished CCS reads as input one needs to `polish` them. I will address the confusion in the upcoming release. If you used the v3.2 guide, stop after `cluster` and use those reads for your tertiary analyses, no need to waste CPU power for additional polishing, as those are already polished. Just make sure you've used `--use-qvs` in `cluster`.

Armin

**Comment by emaleckova** [comment]
Thank you, Armin, this clarifies it all for me.
