### ISSUE TITLE
PBdust should be parallelized

### ISSUE THREAD

**Issue by bruc** [PacificBiosciences/pbbioconda#28]
The initial call to PBdust after building the Dazzler database should be parallelized.

I'm currently working on a large genome, and the initial DBdust step takes about 10 hours because it's a single, serial task. It could be parallelized across the database blocks and the Catrack'ed together. From my own experience, this can work in minutes assuming that Falcon can run a few hundred jobs at once.

**Comment by pb-cdunn** [comment]
Yes. Another solution would be to make DBdust multi-threaded.

Adding a parallel task is harder than it should be because of the difficulty of simultaneous development with other workflow systems, and of maintaining backward compatibility with previous runs.

I'm closing this, but it is on our radar.
