### ISSUE TITLE
Output clarification

### ISSUE THREAD

**Issue by jensbast** [PacificBiosciences/pbbioconda#350]
This is not a bug report, but a question about the output.
I am sorry, I did not find any manual with the details and no publication for IPA yet.
(IPA v1.3.0)

The final folder contains two output files final.p_ctg.fasta and final.a_ctg.fasta.
To me, it is not clear what these are.
The "P" one is the phased assembly, right?
The "A" one is only one copy of the genome (one haplotype with the other removed in a diploid)?

We get a lot of duplicated genes in the "P" and I assumed this means that they are nicely phased. KAT analyses looked good. Or is this wrongly assembled?
How can I identify what scaffold belongs to which haplotype?

If the "A" is after purge_dups, it contains only one haplotype, but not the other (in a diploid), right?

And: great job! This assembler seems to work really well for my animals of interest.

**Comment by isovic** [comment]
Hi Jens,

Thank you, great to hear that it's working well for you!

We should add more clarification to the docs to make it clearer.

Here is some explanation:
- p_ctg - These are primary contigs. The contigs here are not fully phased, i.e. there is likely phase switching in between phased regions (in case the genome is of low heterozygosity, there. can be larger homozygous regions which cannot be spanned by the HiFi reads due to their length).
- a_ctg - These are haplotigs - phased contigs. Also referred to as "alts" or "associate contigs".

For more details on the interpretation of p_ctg and a_ctg please take a look at the FALCON-Unzip publication because the format of IPA's output is very similar to that. The FALCON-Unzip paper has some nice figures depicting this concept: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5503144/

Without long range information, separate haplotigs cannot be scaffolded by IPA alone.
In case you have HiC data, you may want to look at FALCON-Phase which can also be used together with IPA output (because it's compatible to the FALCON-Unzip one).

> If the "A" is after purge_dups, it contains only one haplotype, but not the other (in a diploid), right?

That depends on which folder in the output you are looking at - if it's `19-final`, then this is after purge_dups.
The `p_ctg` in this case are deduplicated primary contigs, while `a_ctg` are a joined set of any haplotigs separated by `purge_dups` from the primary contigs + haplotigs assembled by IPA (in the original `a_ctg` file in `14-separate` folder).

Hope this helps,
Best regards,
Ivan.

**Comment by jensbast** [comment]
Hi Ivan,
thank you very much for your fast reply.
This is very helpful.
Sorry to bother you with still some questions:

So in the 19-final, deduplicated primary contigs  are in the p_ctg. I still have very high level of BUSCO duplicates (75%). Should this not be lower then if it is purge_dups deduplicated?
KAT analyses of the p_ctg suggest to me that haplotypes are nicely phased in there.

I assume, looking at the FALCON publication, that:
- p_ctg should contain the full genome (as a haploid "classical" assembly), and 
- a_ctg the haplotigs (haplotypes) that belong to some phaseable contigs (haplotypes) in the p_ctg

I have 10x (TELL-Seq) long-range info from my samples. Can I use these as well on the haplotigs (a_ctg) and on the full genome (p_ctg)?

Thanks and best wishes,
Jens

**Comment by jensbast** [comment]
And:
As in my case, where the primary contigs are still very duplicated, 
does it make sense to run purge_dups manually on the p_ctg final version?
And then append to the a_ctg file?

Or better do several custom rounds of purge_dups on the RUN/14-seperate/*_ctg.fasta?

Thanks!

**Comment by armintoepfer** [comment]
Closing to due lack of activity.
