### ISSUE TITLE
IPA runtime

### ISSUE THREAD

**Issue by dcopetti** [PacificBiosciences/pbbioconda#367]
Hello,

I am running IPA on a homozygous 11 Gb plant genome and I am wondering if the runtime I have is expected.

The input data is ~24x HiFi reads (19 kb mean size, about 255 GB in a fasta file), the job is running on a single machine (48 CPUs, 1 TB RAM), the command is 
`ipa local --nthreads 12 --njobs 4 --run-dir Hda_i3 -i lib1_all.fa.gz -i lib2_all.fa.gz`
the output folder is 660 GB

It is going since January 2, and the stdout is regularly updated - now it prints this:
```
>|> 20210115 13:18:35.071 -|- INFO -|- Runner -|- 0x7f9192021740|| -|- Loaded all query blocks in 5 sec / 5.43 CPU sec
>|> 20210115 13:18:35.071 -|- INFO -|- Runner -|- 0x7f9192021740|| -|- About to map query blocks: {43}: num_seqs = 226617
>|> 20210115 13:48:06.545 -|- INFO -|- Runner -|- 0x7f0e65bad740|| -|- Mapped query block in 4439 sec / 52570.3 CPU sec.
>|> 20210115 13:48:07.983 -|- INFO -|- Runner -|- 0x7f0e65bad740|| -|- Loading the query blocks: {43}.
>|> 20210115 13:48:12.078 -|- INFO -|- Runner -|- 0x7f0e65bad740|| -|- Loaded the query SeqDB cache block after 4 sec / 4.1 CPU sec
>|> 20210115 13:48:13.428 -|- INFO -|- Runner -|- 0x7f0e65bad740|| -|- Loaded the query SeedDB cache block after 5 sec / 5.45 CPU sec
>|> 20210115 13:48:13.428 -|- INFO -|- Runner -|- 0x7f0e65bad740|| -|- Loaded all query blocks in 5 sec / 5.45 CPU sec
>|> 20210115 13:48:13.428 -|- INFO -|- Runner -|- 0x7f0e65bad740|| -|- About to map query blocks: {43}: num_seqs = 226617
```
is there a way to guess how far we are in the assembly?

Also, due to maintenance I will have to kill this job, I will restart it with `--resume`, but is the assembly going to restart from a checkpoint? E.g. am I going to lose the last 3 days of computation?
Thanks,
Dario

**Comment by zeeev** [comment]
Hi @dcopetti,

Did you start with reads.bam? 

Best,

Zev

**Comment by dcopetti** [comment]
Hi @zeeev,
the input file you mean? No, it was two fastas, made concatenating data from multiple SMRT cells of two different libraries (13 SMRT cells in total).
Does that matter, maybe at the polishing step?

**Comment by ASLeonard** [comment]
I found the mapping stage can take a long time for certain blocks (#357). In some cases, some shards were taking several hundred CPU hours. Repetitive regions seemed to be the suggested cause, so it might be even more noticeable here.

**Comment by pb-cdunn** [comment]
@ASLeonard, **minimap2** (via pbmm2) is no longer used, and that was the known reason for slow-down on repetitive regions. If the environment is up-to-date, this must be a different problem.

**Comment by ASLeonard** [comment]
@pb-cdunn, the latest pbipa available is still v1.3.2 from October in the repo and conda. Is the version without pbmm2 available elsewhere?

**Comment by isovic** [comment]
Hi @dcopetti,

I'm not surprised that it's taking a long time to complete, considering it's a pretty large genome running on a single 48 core machine. Also, it very much depends on the repeat content of the genome.
As an example, for the Redwood genome (~26 Gbp 1N genome size), the overlap stage of IPA took 28625 CPU hours.

> is there a way to guess how far we are in the assembly?

If you are still running the overlapping stage (like in your snippet in the original message), you might be able to estimate the remaining overlap time based on the completed overlap steps.
Run the following to see how many shards there are in total for overlapping: 
```
$ wc -l RUN/03-ovl_asym_prepare/shards/all_shard_ids
```
Then, take a look in the `RUN/04-ovl_asym_run/` folder and check out how many non-empty files called `log.ovl_asym_run.sort.memtime` you can find. The sort happens once all overlap runs in a shard are done.

In any of those shard folders which were fully done, there are one or more log files called "log.ovl_asym_run.pancake.*.memtime". Those contain time measurements for every Pancake run in this folder. If you sum up all the real time values, you'll get a general estimate of how long it took for a single shard to complete.

> Also, due to maintenance I will have to kill this job, I will restart it with --resume, but is the assembly going to restart from a checkpoint? E.g. am I going to lose the last 3 days of computation?

If you resume the job after it was stopped, the assembly will not recompute any of the previously completed jobs. (For example in overlapping, any shard which was done will not be rerun, but those shards which were partially done before the process was killed will start from scratch).


P.S. Did the job perhaps finished running in the meantime?

Best regards,
Ivan.

**Comment by dcopetti** [comment]
Hi Ivan,

Thank you for your feedback.
Unfortunately, it looks like we are still a long way to complete this step. There are 40 `all_shard_ids` files and 24 `log.ovl_asym_run.sort.memtime` files. A set of 4 of them gets produced every 3 days approximately.

I started IPA on this genome since when I assembled it with hifiasm it took three days, so I was hoping for a similarly quick turnaround. I will let this assembly go for now, but I will kill it (and maybe restart it later) if I get more urgent things to run.
Are the steps after 04 still very computationally demanding, or are they faster like e.g. in FALCON?

Do you have any comparison (or approx idea) of how IPA would compare in terms of assembly stats with hifiasm for a plant genome (maize, barley, or something of this level of complexity)?
Thanks,
Dario

**Comment by dcopetti** [comment]
Hi @isovic ,

Eventually, step 04 completed - all 40 log.ovl_asym_run.sort.memtime files have stats on the time it took.
Now I found that the job stopped because there was not enough space:
<img width="928" alt="IPA_no_space" src="https://user-images.githubusercontent.com/13842014/107256033-41875380-6a39-11eb-9cf9-c9e7e3aaae6f.PNG">

As of now, I see that where I am working I have 13 TB free:
`20T  7.3T   13T  37% /scratch`
do you think that indeed step 05 took all that space? I did not have anything else running at the same time.

This is how the run looks like now:
```
(ipa_env) bash-4.2$ ls -lrth Hda_i3/
total 5.0K
-rw-r--r--.  1 copettid mpb  104 Jan  1 22:00 input.fofn
drwxr-xr-x.  2 copettid mpb 4.0K Jan  1 22:00 qsub_log
drwxr-xr-x.  2 copettid mpb 4.0K Jan  1 22:00 01-generate_config
drwxr-xr-x.  2 copettid mpb 4.0K Jan  1 22:50 02-build_db
drwxr-xr-x.  3 copettid mpb 4.0K Jan  1 23:08 03-ovl_asym_prepare
lrwxrwxrwx.  1 copettid mpb   10 Jan 18 08:21 assembly-results -> .snakemake
-rw-r--r--.  1 copettid mpb  218 Jan 18 08:21 config.yaml
drwxr-xr-x. 42 copettid mpb 4.0K Feb  3 17:04 04-ovl_asym_run
drwxr-xr-x.  2 copettid mpb 4.0K Feb  6 18:13 05-ovl_asym_merge
-rw-r--r--.  1 copettid mpb 1.5K Feb  6 18:13 ipa.log
(ipa_env) bash-4.2$ ls -lrth Hda_i3/05-ovl_asym_merge/
total 1.0K
-rw-r--r--. 1 copettid mpb 1.4K Feb  6 18:09 sorted.fofn
-rw-r--r--. 1 copettid mpb 1.6K Feb  6 18:13 log.ovl_asym_merge.mergesort.memtime
(ipa_env) bash-4.2$ du -hs Hda_i3/*
3.0K    Hda_i3/01-generate_config
184G    Hda_i3/02-build_db
22K     Hda_i3/03-ovl_asym_prepare
1.1T    Hda_i3/04-ovl_asym_run
1.5K    Hda_i3/05-ovl_asym_merge
512     Hda_i3/assembly-results
512     Hda_i3/config.yaml
512     Hda_i3/input.fofn
512     Hda_i3/ipa.log
512     Hda_i3/qsub_log
```
Do you think that if I resume the run again I will end up in the same space issue? Are there files that I could delete from folder 04?
More in general, after more than a month (vs 3 days with hifiasm), I wonder if I should still continue with this assembly for this genome.
Any thoughts of if and how to continue?

**Comment by isovic** [comment]
Hi @Dcopetti,

I'm glad to hear that the overlap stage completed!

There is a chance I can make if faster in the future by skipping some obvious local alignments. These repetitive plant genomes are slow to overlap because of those.
Based on my previous experience, the phasing stage should hopefully be faster than overlapping for genomes like this.

I'm surprised that HifiAsm managed to complete the entire assembly in only 3 days. That's very impressive.
On the other hand, an advantage of IPA is that it's designed to run on a cluster where it can leverage larger concurrency.
Also, memory consumption of IPA should be an order of magnitude lower than HifiAsm for genomes like the one you're currently running (even when running the job on single small local nodes).

> Now I found that the job stopped because there was not enough space:

The Linux `sort` command uses a temporary directory to sort files, and by default it uses the `/tmp` directory. Sometimes the `/tmp` can run out of space (for example, other users/processes may have consumed it, or someone hasn't cleaned up after themselves).

> do you think that indeed step 05 took all that space?

No, that's fine. The `/tmp` is probably not mounted on your `/scratch`, otherwise you'd have plenty of space.

> Do you think that if I resume the run again I will end up in the same space issue? Are there files that I could delete from folder 04?

You can definitely resume it, but it's important that you specify a different temporary directory first to prevent the same issue from happening again.

For example, when running an assembly, use the following option:
`ipa --tmp-dir "./" --resume ...`
This will set the temporary directory to the current running directory of the task instead of the default `/tmp` that the standard `sort` command uses.

Before you run this, I just want to verify that your `RUN/04-ovl_asym_run/*/` folders still contain overlap files (those are marked as temporary in our Snakemake workflow and should get removed by Snakemake only after the `05-ovl_asym_merge` stage is successfully completed.
For example, any folder in `RUN/04-ovl_asym_run` should look something like this:
```
$ ls RUN/04-ovl_asym_run/0/
log.ovl_asym_run.pancake.s0.b0_0_1.memtime log.ovl_asym_run.sort.memtime ovl.sorted.m4
```
(with a `ovl.sorted.m4` file in it.)

> More in general, after more than a month (vs 3 days with hifiasm), I wonder if I should still continue with this assembly for this genome.

If possible, I would definitely be interested to see this genome being fully assembled by IPA.
Based on your feedback I see at least two improvements we can make so far:
- Set the default temp directory to "./".
- Improve overlap speed for very repetitive genomes by prefiltering some clear local alignments.

Perhaps if you run this assembly all the way there might be some more valuable feedback you can give us.

Thank you!

Best regards,
Ivan.

**Comment by dcopetti** [comment]
Hi Ivan,

Thank you for the feedback,
Regarding step 04, inside `04-ovl_asym_run/*/` I have 40 `ovl.sorted.m4` and `log.ovl_asym_run.sort.memtime` (same number as the folders) files, but 101 `*memtime` files (there are from 1 to 10 such files in each - is that OK?)
Do I need to delete fold 05?

I can definitely change the tmp directory when I resume this assembly, however I have to wait a bit since I have jobs with more priority going on now. I will get back to you with the final assembly.

As for the comparison with hifiasm, I have to correct myself: the assembly took 3 days on a machine with 96 CPUs (vs 48 here) - equivalent to 6 days on the machine where I am running IPA. Still a clear difference though.
Cheers,
Dario

**Comment by zeeev** [comment]
V1.5.0 is publicly available now.
