### ISSUE TITLE
falcon unzip example config needs update

### ISSUE THREAD

**Issue by mp15** [PacificBiosciences/pbbioconda#42]
**Operating system**
Linux specifically RHEL 7.4

**Package name**
FALCON-unzip

**Describe the bug**
The current version of FALCON unzip uses minimap2 rather than blasr in the phasing step, significantly reducing resource requirements and allowing greater parallelism. The ```[job.step.unzip.blasr_aln]``` section of https://github.com/PacificBiosciences/pb-assembly/blob/master/cfgs/fc_unzip.cfg does not reflect this and constrains the pipeline to running 2 jobs at a time whilst requesting large amounts of memory.

**Expected behavior**
The FALCON unzip example config should reflect resource requirements typical of the current version of the pipeline.

**Comment by skingan** [comment]
Updated:

# uses minimap2 now
[job.step.unzip.blasr_aln]
njobs=16
NPROC=2
MB=16384

**Comment by akaraw** [comment]
Attention to Sarah Kingan:
time minimap2 -a -x map-pb -t ${threads_aln} /gpfs1/scratch/***/3-unzip/reads/000001F/ref.fa /gpfs1/scratch/30days/***/3-unzip/reads/000001F/reads.fa > tmp_aln.sam
+ minimap2 -a -x map-pb -t 24 /gpfs1/scratch/***/3-unzip/reads/000001F/ref.fa /gpfs1/scratch/***/3-unzip/reads/000001F/reads.fa
Hi Sarah,
Above is a snippet from a recent fc_unzip.py run and minimap2 running with -t 24!. Is it possible to change this value since I do not have such resources. I only can go up to -t 12?

Thank you in advance
