### ISSUE TITLE
Trouble in "graph annotation and haplotig" step in FALCON-Unzip

### ISSUE THREAD

**Issue by ke-shi** [PacificBiosciences/pbbioconda#44]
We are working on a plant with 2.2 Gb genome. The FALCON assembly was completed with 107 Gb Sequel reads (~50x), but FALCON-Unzip failed at the "graph annotation and haplotig" step of a contig, saying:

> Exception: Call 'nucmer -mum p_ctg.002484F.fa h_ctg_all.002484F.fa -p hp_aln' returned 256.

It looks abortion in nucmer process because the primary contig (p_ctg) size in 1-hasm/ was 0.

The FALCON-Unzip always failed at this contig even we tried again and again.

How should we fix it? Or, can we skip this contig?

**Comment by isovic** [comment]
Hi,
Which version of the FALCON and Unzip tools are you using, and have you installed them from Bioconda?
Also, which version of MUMmer do you have available?
I believe this line of code is deprecated for several releases of Unzip...
Best regards,
Ivan.

**Comment by ke-shi** [comment]
Hi Ivan,

We used falcon-2017.11.02-16.04-py2.7-ucs2 and MUMmer3.23.

FALCON-Unzip was failed with parameters:
```
pa_HPCdaligner_option = -v -B128 -e0.75 -M32 -l1900 -k14 -h256 -w8 -s100 -t14
ovlp_HPCdaligner_option = -v -B128 -M32 -k24 -h1024 -e.96 -l2500 -s100
pa_DBsplit_option = -x500 -s400
```
but completed with
```
pa_HPCdaligner_option = -v -B128 -e0.75 -M24 -l1900 -k14 -h128 -w8 -s100 -t14
ovlp_HPCdaligner_option = -v -B128 -M24 -k24 -h1024 -e.96 -l2500 -s100
pa_DBsplit_option = -a -x500 -s400
```
seems it depends on parameters... Correct?

**Comment by isovic** [comment]
Hi,
Different overlapping parameters have a direct impact on the set of contigs that are generated in FALCON, and subsequently processed in FALCON-Unzip. Unzip also uses the overlaps generated in the initial stage, and this is likely the reason your process completed successfully with a different set of parameters.
Though, it should not fail like it did in any case, and thank you for reporting the bug.

FALCON-Unzip has been updated since version 2017.11.02, and the latest version can be found on Bioconda. This version should not suffer from the issue you are experiencing.
Please note that the new version is not compatible with the intermediate results of the version you are using, so you cannot upgrade mid-run and continue the process with the new version. Instead, may I recommend that you switch to the new version when starting an assembly from the beginning.

Since this issue refers to a deprecated version (which is not available on Bioconda), and has already been resolved in the newer versions, I will close it. In case there is any need, please reopen the issue.

Best regards,
Ivan.
