### ISSUE TITLE
Mas-Seq analysis for Drosophila sample

### ISSUE THREAD

**Issue by JessicWu** [PacificBiosciences/pbbioconda#556]
**Operating system**
Which operating system and version are you using?

Shared computing cluster / Linux Shell

**Package name**
Which package / tool is causing the problem? Which version are you using, use `tool --version`. Have you updated to the latest version `conda update package`? Have you updated the complete env by running `conda update --all`? Have you ensured that your channel priorities are set up according to the bioconda recommendations at https://bioconda.github.io/#set-up-channels?

CLI workflow was used to analyze the Mas-seq data which is described here: https://isoseq.how/umi/cli-workflow.html and https://isoseq.how/classification/workflow.html. All the packages are most updated version.

**Conda environment**
What is the result of `conda list`? (Try to paste that between [triple backticks](https://help.github.com/articles/creating-and-highlighting-code-blocks/).)
'''
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
_openmp_mutex             5.1                       1_gnu
ca-certificates           2022.10.11           h06a4308_0
certifi                   2020.6.20          pyhd3eb1b0_3
isoseq3                   3.8.0                h9ee0642_0    bioconda
libffi                    3.3                  he6710b0_2
libgcc-ng                 11.2.0               h1234567_1
libgomp                   11.2.0               h1234567_1
libstdcxx-ng              11.2.0               h1234567_1
lima                      2.6.0                h9ee0642_0    bioconda
ncurses                   6.3                  h5eee18b_3
pbmm2                     1.9.0                h9ee0642_0    bioconda
pbpigeon                  1.0.0                hdfd78af_0    bioconda
pbskera                   0.1.0                hdfd78af_0    bioconda
pip                       19.3.1                   py27_0
python                    2.7.18               ha1903f6_2
readline                  8.2                  h5eee18b_0
setuptools                44.0.0                   py27_0
sqlite                    3.40.0               h5082296_0
tk                        8.6.12               h1ccaba5_0
wheel                     0.37.1             pyhd3eb1b0_0
zlib                      1.2.13               h5eee18b_0
'''
conda
**Describe the bug**

Pigeon -classify doesn't work for Drosophila. Two versions of reference Genome and matched Annotation for Drosophila have been tried and neither worked. The warning was received showing with following as a example "| 20221124 14:43:28.600 | WARN | Skipping reference (211000022278032) - missing from reference annotations". However, these reference genome and annotation work for the short reads analysis.

**Error message**
Paste the error message / stack.

For Latest Flybase release:
![image](https://user-images.githubusercontent.com/82911765/211006317-0e793ff8-d661-4b1d-91e8-b682ff4f2bdd.png)

For the older version:
| 20221124 14:43:28.600 | WARN | Skipping reference (211000022278032) - missing from reference annotations
| 20221124 14:43:28.601 | WARN | Skipping reference (211000022278047) - missing from reference annotations
| 20221124 14:43:28.601 | WARN | Skipping reference (211000022278089) - missing from reference annotations
| 20221124 14:43:28.601 | WARN | Skipping reference (211000022278090) - missing from reference annotations
...
![image](https://user-images.githubusercontent.com/82911765/211009008-a46d2d2e-8bfe-4c20-a4b9-22db942722a2.png)
![image](https://user-images.githubusercontent.com/82911765/211009039-93e3bd4e-1168-4068-9959-1b72f6702ab9.png)

**To Reproduce**
Steps to reproduce the behavior. Providing a minimal test dataset on which we can reproduce the behavior will generally lead to quicker turnaround time!

**Expected behavior**

The Pigeon --classify works with the final proper output matirx.

**Comment by derekwbarnett** [comment]
Hi @JessicWu . Did you run `pigeon sort` and/or `pigeon index` on the input reference annotations? 
https://isoseq.how/classification/workflow#index-the-reference-files

**Comment by JessicWu** [comment]
Dear Derek,

Thanks a lot for the speedy reply.

Yes, the Pigeon --index was applied to the annotation.gtf and samtools
--faidx on the reference.fasta.

Please let me know if further info is needed.

Best,
Yan

**Comment by JessicWu** [comment]
Dear Armin,

Thanks for the reply.

Please let me know how you like the minimal working dataset to be. I will
be extremely grateful if you can provide some instructions on how to create
this dataset.

Best,
Yan

**Comment by JessicWu** [comment]
Hi Armin,

Thanks a lot for the reply.

Should I provide the raw bam data from Sequencer or the deduplicated bam
data before the mapping step?

Best,
Yan

**Comment by derekwbarnett** [comment]
You could also start smaller, with just the pigeon inputs: the transcripts from isoseq collapse and any reference files. That may be sufficient, since pigeon is the only step looking at annotation GTFs.

**Comment by greensii** [comment]
FYI - i have this same exact problem with a GTF file for Arabidopsis thaliana.  `pigeon classify` assigns all transcripts as intergenic, and `pigeon make-seurat` creates empty matrices.

is there a specific GTF format that's required for this to work?
here are the first few lines of my GTF:

> Chr1    Araport11       gene    3631    5899    .       +       .       transcript_id "AT1G01010"; gene_id "AT1G01010";
Chr1    Araport11       mRNA    3631    5899    .       +       .       transcript_id "AT1G01010.1"; gene_id "AT1G01010";
Chr1    Araport11       five_prime_UTR  3631    3759    .       +       .       transcript_id "AT1G01010.1"; gene_id "AT1G01010";
Chr1    Araport11       exon    3631    3913    .       +       .       transcript_id "AT1G01010.1"; gene_id "AT1G01010";
Chr1    Araport11       CDS     3760    3913    .       +       0       transcript_id "AT1G01010.1"; gene_id "AT1G01010";
Chr1    Araport11       protein 3760    5630    .       +       .       transcript_id "AT1G01010.1"; gene_id "AT1G01010";
Chr1    Araport11       exon    3996    4276    .       +       .       transcript_id "AT1G01010.1"; gene_id "AT1G01010";
Chr1    Araport11       CDS     3996    4276    .       +       2       transcript_id "AT1G01010.1"; gene_id "AT1G01010";
Chr1    Araport11       exon    4486    4605    .       +       .       transcript_id "AT1G01010.1"; gene_id "AT1G01010";
Chr1    Araport11       CDS     4486    4605    .       +       0       transcript_id "AT1G01010.1"; gene_id "AT1G01010";

**Comment by greensii** [comment]
update: something about the GTF formatting seems to be the issue. Just tried with a different GTF for the same reference fasta, containing mostly the same annotations but `transcript` instead of `mRNA` in the 3rd column, and different tag sets in the 9th column annotation field.  now it works fine.  first few lines of the working GTF copied below:

> Chr1    phytozomev12    gene    3631    5899    .       +       .       gene_id "AT1G01010.Araport11.447"; ID "AT1G01010.Araport11.447"; Name "AT1G01010";
Chr1    phytozomev12    transcript      3631    5899    .       +       .       gene_id "AT1G01010.Araport11.447"; transcript_id "AT1G01010.1.Araport11.447"; ID "AT1G01010.1.Araport11.447"; Name "AT1G01010.1"; Parent "AT1G01010.Araport11.447"; geneName "NAC001"; longest "1"; original_biotype "mrna"; pacid "37401853";
Chr1    phytozomev12    exon    3631    3913    .       +       .       gene_id "AT1G01010.Araport11.447"; transcript_id "AT1G01010.1.Araport11.447"; ID "AT1G01010.1.Araport11.447.exon.1"; Parent "AT1G01010.1.Araport11.447"; pacid "37401853";
Chr1    phytozomev12    exon    3996    4276    .       +       .       gene_id "AT1G01010.Araport11.447"; transcript_id "AT1G01010.1.Araport11.447"; ID "AT1G01010.1.Araport11.447.exon.2"; Parent "AT1G01010.1.Araport11.447"; pacid "37401853";
Chr1    phytozomev12    exon    4486    4605    .       +       .       gene_id "AT1G01010.Araport11.447"; transcript_id "AT1G01010.1.Araport11.447"; ID "AT1G01010.1.Araport11.447.exon.3"; Parent "AT1G01010.1.Araport11.447"; pacid "37401853";
Chr1    phytozomev12    exon    4706    5095    .       +       .       gene_id "AT1G01010.Araport11.447"; transcript_id "AT1G01010.1.Araport11.447"; ID "AT1G01010.1.Araport11.447.exon.4"; Parent "AT1G01010.1.Araport11.447"; pacid "37401853";
Chr1    phytozomev12    exon    5174    5326    .       +       .       gene_id "AT1G01010.Araport11.447"; transcript_id "AT1G01010.1.Araport11.447"; ID "AT1G01010.1.Araport11.447.exon.5"; Parent "AT1G01010.1.Araport11.447"; pacid "37401853";
Chr1    phytozomev12    exon    5439    5899    .       +       .       gene_id "AT1G01010.Araport11.447"; transcript_id "AT1G01010.1.Araport11.447"; ID "AT1G01010.1.Araport11.447.exon.6"; Parent "AT1G01010.1.Araport11.447"; pacid "37401853";
Chr1    phytozomev12    CDS     3760    3913    .       +       0       gene_id "AT1G01010.Araport11.447"; transcript_id "AT1G01010.1.Araport11.447"; ID "AT1G01010.1.Araport11.447.CDS.1"; Parent "AT1G01010.1.Araport11.447"; pacid "37401853";
Chr1    phytozomev12    CDS     3996    4276    .       +       2       gene_id "AT1G01010.Araport11.447"; transcript_id "AT1G01010.1.Araport11.447"; ID "AT1G01010.1.Araport11.447.CDS.2"; Parent "AT1G01010.1.Araport11.447"; pacid "37401853";
(

**Comment by armintoepfer** [comment]
@Magdoll @derekwbarnett please have a look

**Comment by derekwbarnett** [comment]
@gushiro Yeah, pigeon is only looking for the "transcript" label, not "mRNA". That's a straightforward add, and we can definitely have that in the next release. I'll check back with the UTR handling and see what might be happening.

**Comment by gushiro** [comment]
@derekwbarnett did you guys manage to update the software so it reads UTRs better? An option to consider "N" nucleotides after the last exon as part of the UTR of that gene would be great.

**Comment by derekwbarnett** [comment]
@gushiro Apologies on the delayed response. But no, `pigeon` doesn't have any special considerations for UTRs, especially with messy annotation boundaries. It is primarily interested in "transcript"/"exon" annotations only. If we see a pattern of these annotations becoming an issue, we will consider addressing it.

That said, we have since released an update that does fix some "intergenic" overcalls. Please see if that improves your results.
