### ISSUE TITLE
Segmentation Fault - Isoseq3

### ISSUE THREAD

**Issue by maaraujo10** [PacificBiosciences/pbbioconda#568]
I am running Isoseq3 in a cluster, I have tried installing using both linux binaries and the bioconda package.

**Package name**
Isoseq3

**Conda environment**
Conda list result:
# Name                    Version                   Build  Channel
isoseq3                   3.8.2                h9ee0642_0    bioconda
lima                      2.7.1                h9ee0642_0    bioconda

**Describe the bug**
When I try to run isoseq3 in any way, I get an error.
commands tried:
1. isoseq3 cluster
2. isoseq3 refine
3. isoseq3 -h
4. isoseq3 cluster -h 
5. isoseq3
6. isoseq3 --version

**Error message**
All above listed commands give the same error, in either the binary or bioconda installation.
Error is:
Segmentation fault

**Expected behavior**
As other packages one would expect a help message displaying options for any of the above commands

**Comment by armintoepfer** [comment]
What OS and kernel are you using?

**Comment by rsharris** [comment]
I have the same problem. Installed from bioconda earlier today. isoseq3 seems to segfault right away regardless of what's the rest of the command line looks like.

I installed this earlier today in a fresh conda environment.
isoseq3-3.8.2  h9ee0642_0 1.6 MB  bioconda

Am trying to do perform the steps at https://isoseq.how/clustering/cli-workflow.html , but have been advised to use isoseq3 instead of isoseq. I successfully ran step 2 which uses lima. At step 3 I try isoseq3 refine and get the segfault.

uname -a
Linux fletony 4.19.0-21-amd64 #1 SMP Debian 4.19.249-2 (2022-06-30) x86_64 GNU/Linux

**Comment by jamestwebber** [comment]
I'm also seeing this again on a new machine, same as back in #549...

Output of `uname`:
```Linux 4.19.0-23-cloud-amd64 #1 SMP Debian 4.19.269-1 (2022-12-20) x86_64 GNU/Linux```

**Comment by rsharris** [comment]
Thanks @jamestwebber . Unfortunately the binary doesn't work for me. I just get "Illegal instruction" instead of a segfault.

**Comment by armintoepfer** [comment]
Illegal instructions means that you are using an ancient CPU that does not support SSE4.1

**Comment by armintoepfer** [comment]
@jamestwebber it's strange what conda did to the binary. I'll try to re-upload it...

**Comment by rsharris** [comment]
@armintoepfer
> Illegal instructions means that you are using an ancient CPU that does not support SSE4.1

Inferring from what I see above, the conda package doesn't rebuild isoseq3, it merely loads a binary (am I correct?). In which case even if the conda package's isoseq3 didn't segfault, I'd still have the illegal instruction issue. Right?

As for why I was running on such an old CPU, I was running on the primary machine attached to disk where my sequenced data is. The only restriction I noticed (when I was reading installation instructions) was that I needed my bioconda environment to be python 2.7.

I need to ask, then, if I locate a machine that supports SSE4.1 should that be sufficient?

**Comment by armintoepfer** [comment]
For Iso-Seq, you don't need python. Just a machine that isn't older than from ~2007.

**Comment by rsharris** [comment]
@armintoepfer &J.

**Comment by philoel** [comment]
> The solution from back then worked for me now (downloaded the binaries directly) but it would be really nice if the conda packages actually worked.

since I'm getting a Segfault too, could we write here how we can go about downloading and then using the binaries directly? This sounds pretty magical but also mysterious!

Maybe it helps the next person who needs to download binaries too, but doesn't have the experience to know what's involved in this.

**Comment by rsharris** [comment]
https://github.com/PacificBiosciences/pbbioconda/issues/549#issuecomment-1344516742

**Comment by rsharris** [comment]
But I would guess when the latest version number changes, you'd have to consider that when you download the binary.

**Comment by armintoepfer** [comment]
I have uploaded a new version. If that still segfaults, but not the github binary itself, then conda is corrupting the binary.
