### ISSUE TITLE
Falcon: parameters to optimize haplotype resolution

### ISSUE THREAD

**Issue by gbdias** [PacificBiosciences/pbbioconda#57]
Hi,

- I have been using Falcon with pb-assembly (0.0.1, and 0.0.2) to assemble a few different genomes (from 14 Mbp to 200 Mbp).
- When I used HGAP4 (which also runs Falcon) on the same datasets I noticed that the average and total size of the **a_ctgs** is larger in the HGAP4 output. This is consistent across different datasets I have tested (example below).

<img width="623" alt="screen shot 2018-12-05 at 1 16 15 pm" src="https://user-images.githubusercontent.com/7614153/49534640-fe952880-f88f-11e8-96aa-c63600392cf4.png">

- I tried adjusting the Falcon assembly parameters to match those used by HGAP4, namely `length_cutoff_pr`, `pa_daligner_option`, `ovlp_daligner_option`, `pa_DBsplit_option`, `falcon_sense_option` and `overlap_filtering_setting`. However, HGAP4 still produces larger a_ctgs.
- Do you have any idea why? Is there something algorithmically different between the Falcon versions used by HGAP and pb-assembly?

Thanks,
Guilherme

**Comment by mp15** [comment]
I have a similar issue but with my primary contigs rather than associate ones. Supplying both the same parameters to HGAP 4 (from SMRTlink 5.1) and pb-assembly (0.0.1) from conda produces two assemblies with differing contig N50 values. HGAP 4 yields a p_ctg N50 of 13 megabases, whilst FALCON yields 11 megabases. Unfortunately I cannot seem to figure out what has been changed between these two versions of what is essentially the same pipeline to cause this result and I would really rather use the FALCON result so that I can unzip it.
