### ISSUE TITLE
CL: Annotation of alignment classes 

### ISSUE THREAD

**Issue by meryyr** [PacificBiosciences/pbbioconda#675]
Hi,
I was wondering how the classification (CL) of the fusions detected by pbfusion is inferred. For example, based on what do you classify a fusion as PotentialTransSplicing, or as FUSION ? 
I hope my question is clear, let me know if not :)

Thank you for your help!

**Comment by PB-DB** [comment]
Hi,

Great question!

We classify genes as potential trans splicing as genes which have high numbers ( >= 8 by default) of candidate partners, for which none of the candidate partners overlap with the potential trans splicing gene.

We also mark these as low quality if the expected coverage on partner genes mismatches significantly, in addition to the standard pbfusion filtering criteria.

Happy to answer any further questions,

Daniel

**Comment by meryyr** [comment]
> Hi,
> 
> Great question!
> 
> We classify genes as potential trans splicing as genes which have high numbers ( >= 8 by default) of candidate partners, for which none of the candidate partners overlap with the potential trans splicing gene.
> 
> We also mark these as low quality if the expected coverage on partner genes mismatches significantly, in addition to the standard pbfusion filtering criteria.
> 
> Happy to answer any further questions,
> 
> Daniel

Thank you so much for your answer!! And what about the Fusions, Sense Antisense and Overlap classes? What are the criteria to classify fusions, found by pbfuson, in one of these classes ?

**Comment by PB-DB** [comment]
I'm closing this for now - feel free to re-open with more questions!

We plan to extend the documentation to include this with the next release.

**Comment by meryyr** [comment]
> I'm closing this for now - feel free to re-open with more questions!
> 
> We plan to extend the documentation to include this with the next release.

Thank you so much for the exhaustive explanation about the classes!
I actually do have another question, how do you discriminate between LOW and MEDIUM fusions? (the minimum fusion quality to emit). In particular what are the parameters that you look at to say that a fusion is of MEDIUM quality? Thank you again!

**Comment by PB-DB** [comment]
Hi Maria,

Great question.

LOW is assigned when a candidate fusion is readthrough, between overlapping genes, or fails other QC tests.

These tests are:

1. Too many genes (> 3)
2. Too few reads supporting (< 2).
3. Minimum identity on either side of the breakpoint is too low (< 85%)
4. Breakpoint median distance is too high - this means the breakpoint isn't well-defined, or there are multiple events with nearby breakpoints being grouped together. (> 1000)
5. Minimum mapq on either side (disabled by default, but can be raised > 0 with `--min-min-mapq`.


These can all be tweaked via command-line options, but they work pretty well.

If a candidate is marked as MEDIUM (not in any of those failing cases), and it is found in the Mitelman database, we mark it as high quality. There are issues with Mitelman - many events seem to be readthroughs rather than true fusions - but it's still useful because it is at least in the literature.

Let me know what further questions you may have.

Thanks,

Daniel

**Comment by meryyr** [comment]
> Mitelman

Hi Daniel! Thank you again for the very clear and fast answer!
