### ISSUE TITLE
the number of reads pre and post running "isoseq refine"

### ISSUE THREAD

**Issue by WQQIGDB** [PacificBiosciences/pbbioconda#708]
Hi, 
The number of "Full-Length Non-Chimeric Reads" reduced nearly half from "Full-Length Reads". Is this normal? 
I started my isoseq pipeline with the raw subreads data and have run the first few steps: 
(1) CCS calling: `ccs m54067_190809_002958.subreads.bam m54067_190809_002958.ccs.1.bam --log-level INFO --report-json example.report.json --hifi-summary-json example.hifi_summary.json --log-file example.ccs.log --report-file example.report.txt --metrics-json example.zmw_metrics.json.gz --chunk 1/10`; 
(2) Primer removal and demultiplexing: `lima --isoseq m54067_190809_002958.ccs.bam TeloPrime_V2_primer.fasta m54067_190809_002958.fl.bam`; 
(3) Refine: `isoseq refine m54067_190809_002958.fl.TeloPrimeModified_5p--TeloPrimeModified_3p.bam TeloPrime_V2_primer.fasta m54067_190809_002958.flnc.bam --require-polya`; 
The library is built from TeloPrime Full-Length cDNA Amplification Kit V2. Here is the contents of my primer.fasta file: 
>TeloPrimeModified_5p
TGGATTGATATGTAATACGACTCACTATAG
>TeloPrimeModified_3p
CGCCTGAGA

The following is the summary report after running isoseq refine:
{
    "_comment": "Created by pbcopper v2.3.99",
    "attributes": [
        {
            "id": "sample_name",
            "name": "Sample Name",
            "value": ""
        },
        {
            "id": "num_reads_fl",
            "name": "Full-Length Reads",
            "value": 284393
        },
        {
            "id": "num_reads_flnc",
            "name": "Full-Length Non-Chimeric Reads",
            "value": 135263
        },
        {
            "id": "num_reads_flnc_polya",
            "name": "Full-Length Non-Chimeric Reads with Poly-A Tail",
            "value": 123504
        }
    ],
    "dataset_uuids": [],
    "id": "isoseq_refine",
    "plotGroups": [],
    "tables": [],
    "title": "Iso-Seq Refine Report",
    "uuid": "8f1243dd-7d26-425e-8031-236ec6aecd6e",
    "version": "1.0.1"
}
Is there something wrong here? 
Thanks!

**Comment by WQQIGDB** [comment]
Anyone can give me some suggestions, please?

**Comment by WQQIGDB** [comment]
> Have you solved the problem now? Because the first time I was dealing with three generations of data, I had the same problem. Thank you!

Not yet now. 
I followed the procedure pasted on [https://isoseq.how/clustering/examples.html](url) and [https://databeauty.com/blog/tutorial/2020/12/08/PacBio-Iso-Seq-Data-Analysis.html](url). But it happens like what I described above. I don't know if it is normal.
If you have some new findings, let me know please!

**Comment by armintoepfer** [comment]
This is not a technical issue with out bioconda binaries. Please reach out to PacBio's support.

**Comment by ccalix** [comment]
For those encountering a big difference in the number of reads pre and post running "isoseq refine": **have you checked the number of polyT-containing reads in the lima output?**. These kind of reads could explain why you have a huge drop in the number of reads after isoseq refine --require-polya. PolyT-containing reads are reverse-complement of polyA-containing RNAs, which should have been reoriented by lima. If they were not reoriented, they are being removed by --require-polya. I talk a bit more about this issue here: https://github.com/PacificBiosciences/pbbioconda/issues/770. I also followed the real-world example provided here: https://isoseq.how/umi/examples.html, and observed the same behaviour.
Now, my question is: why is lima not orienting the sequences to the 5′→3′ direction in the datasets I analysed?
