### ISSUE TITLE
Aborting assembly and using new pa_REPmask_code and daligner options

### ISSUE THREAD

**Issue by nsgarcia27** [PacificBiosciences/pbbioconda#82]
Hello, 

I am currently assembling a plant (grass) genome which is expected to have a high repetitive DNA content. The current setting I used for repeat masking seems daligner seems to be taking up a lot of storage space and spawning too many jobs. Is there a way to modify the config file to a new pa_REPmask_code and pa_daligner_option parameters without totally starting again from the beginning?

Thank you

Nelson

**Comment by pb-cdunn** [comment]
If you are using **pypeFLOW**, then yes. (If you use **pbsmrtpipe** or the new **Cromwell** workflow, then no.) Simply delete the `rep` directories under `0-rawreads/`, then restart.

Do *not* delete the entire `0-rawreads/` directory. The important thing is not to touch `0-rawreads/build/`, for if you alter that, then the number of blocks could change, which would mean a different set of daligner job-dirs. But changing rep-dirs is safe because that only affects the mask-tracks.

To verify that you are using the new mask-tracks, you can go into a running daligner unit-of-work (e.g. `0-rawreads/daligner-runs/j_0001/uow-00`) and run `DBdump -mdust -mtan -mrep0 -mrep1 -mrep2 raw_reads.db` (or however many rep-tracks you have). (You might need the full-path to the `.db` depending on your version; it might be symlinked into your directory.) Try `DBdump` for help.
