### ISSUE TITLE
missing M5 from using latest pbmm2 Docker code

### ISSUE THREAD

**Issue by Arkarachai** [PacificBiosciences/pbbioconda#96]
I used pbmm2 to map BAM to the assembled genome and polish by SMRT6.0 polishing. This is https://quay.io/repository/biocontainers/pbmm2?tab=tags 0.12.0--ha87ae23_0 which is the latest and less than 1 month. However, the M5 field is missing from the minimap output, so I can't use them for polishing. Do you know how to fix this? Are you strictly update only the Conda one?
The bioconda page https://bioconda.github.io/recipes/pbmm2/README.html mentioned that we can docker pull from Quay. I think it would be good if Pacbio also supports the docker as it is increasingly popular in the bioinformatics community.

**Comment by armintoepfer** [comment]
You can't mix and match latest software from conda with official releases. Please stick to one release channel. If you use GenomicConsensus with pbmm2 from conda, polishing will succeed.

What "support" would you expect for docker? Most of our tools are on bioconda, what you make out of it, is up to you.

**Comment by Arkarachai** [comment]
@armintoepfer We have some PYTHONPATH issue in our setup, so probably have to go with Bioconda route. I'm very surprised though that the official release and Conda are not compatible. Would Pacbio plan to maintain these two parallel version?

**Comment by pb-dseifert** [comment]
because keeping them aligned would require tons more resources. Bioconda has no service-level agreements, and we provide this service to the community, without any concrete promises.

**Comment by armintoepfer** [comment]
Those are two different worlds. One is cut fresh from development HEAD, the other goes through official vetting and consequently can lag behind quite a bit. Cherry picking works sometimes, but no promise, because interfaces will break and if, we make sure that software from the same source works together.
The choice is yours. You pick the blue pill, you get stable releases with official tech support. You pick the red pill, you stay in conda land, get the latest and greatest versions, but might trigger a few more bugs here and there.

That's all I have to say about this topic.
